zuul:
  routes:
    spring-cloud-web: #随便写的
      path: /order/**
      serviceId: spring-cloud-web
    spring-cloud-web-security: #随便写的
      path: /order/security/**
      serviceId: spring-cloud-web-security
    api-gateway:
      path: /local/**
      url: forward:/local #路由到本地
    blog:
      path: /blog/**
      url: http://localhost:9092/
#  sensitive-headers: ["xxx", "sdfsdf"]
