zuul:
  routes:
    spring-cloud-web: #随便写的
      path: /order/**
      serviceId: spring-cloud-web
    spring-cloud-web-security: #随便写的
      path: /security/order/**
      serviceId: spring-cloud-web-security
    api-gateway:
      path: /local/**
      url: forward:/local #路由到本地
    blog:
      path: /blog/**
      url: http://localhost:9092/
    spring-cloud-auth-server:
      path: /auth/**
      serviceId: spring-cloud-auth-server
    spring-cloud-auth-server-db:
      path: /db/auth/**
      serviceId: spring-cloud-auth-server-db
#  sensitive-headers: ["xxx", "sdfsdf"]
