db:
  name: '{cipher}AQAgbnTc3sNpjctGjDY8IdQMJSfrgP3Y5dNJhIU7o/YFGtfoWanB3TPMExjMX4kPtLc4T61myZ8yl5SvASmigYiQKfvF5A/ql/EkIeZxyDbodx0o4Eyp20If2jn5K1aQWKq17TeIqc+3qGLv3TSvcwSRv77RuulVRzt9Ubav8yr/hCq3BMRlQv5TBq6Ubq8TSQoK8DFgYktBECtB5f697dHdZaa2s4toBqCevGllVd+YdLSZ+Tr274/zaPk8ejL+XNxFBNe4xl8eSxgpBP4Xb8q95cvzb9fLzqlRCNuknfH7eyf7DZWlHlm0vwz5frVLwifppuSTelDxPakrKVPJu3VLHOhxxtDPx1ECM8Ac+uIysHkFY3vVCJHrOF8e38R0ghk='
  user: root
